FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY HelpDeskHero.slnx ./

COPY src/HelpDeskHero.Shared/HelpDeskHero.Shared.csproj src/HelpDeskHero.Shared/
COPY src/HelpDeskHero.UI/HelpDeskHero.UI.csproj src/HelpDeskHero.UI/

RUN dotnet restore src/HelpDeskHero.UI/HelpDeskHero.UI.csproj

COPY . .

RUN dotnet publish src/HelpDeskHero.UI/HelpDeskHero.UI.csproj \
    -c Release \
    -o /app/publish

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html

COPY --from=build /app/publish/wwwroot .
COPY --from=build /src/src/HelpDeskHero.UI/wwwroot/appsettings.Docker.json ./appsettings.json
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80