FROM mcr.microsoft.com/dotnet/sdk:10.0.203 AS build
WORKDIR /src

COPY TixeNex.slnx ./

COPY src/TixeNex.Shared/TixeNex.Shared.csproj src/TixeNex.Shared/
COPY src/TixeNex.UI/TixeNex.UI.csproj src/TixeNex.UI/

RUN dotnet restore src/TixeNex.UI/TixeNex.UI.csproj

COPY . .

RUN dotnet publish src/TixeNex.UI/TixeNex.UI.csproj \
    -c Release \
    --no-restore \
    -o /app/publish

FROM nginx:1.29.7-alpine AS final
WORKDIR /usr/share/nginx/html

COPY --from=build /app/publish/wwwroot .
COPY --from=build /src/src/TixeNex.UI/wwwroot/appsettings.Docker.json ./appsettings.json
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
