FROM mcr.microsoft.com/dotnet/sdk:10.0.203 AS build

WORKDIR /src

COPY TixeNex.slnx ./

COPY src/TixeNex.Shared/TixeNex.Shared.csproj src/TixeNex.Shared/
COPY src/TixeNex.Api/TixeNex.Api.csproj src/TixeNex.Api/
COPY src/TixeNex.Worker/TixeNex.Worker.csproj src/TixeNex.Worker/

RUN dotnet restore src/TixeNex.Worker/TixeNex.Worker.csproj

COPY . .

RUN dotnet publish src/TixeNex.Worker/TixeNex.Worker.csproj \
    -c Release \
    -o /app/publish \
    --no-restore \
    /p:UseAppHost=false \
    /p:BuildInParallel=false \
    -m:1

FROM mcr.microsoft.com/dotnet/aspnet:10.0.7 AS final

WORKDIR /app

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "TixeNex.Worker.dll"]
